import express from "express";
import { index } from "../controllers";
import userRoutes from "./userRoutes";
import blogRoutes from "./blogRoutes";
import { swaggerSpec, swaggerUi } from "../configs/docs/swagger";
import contactRoutes from "./contactRoutes";
import productsRoutes from "./productsRoutes";
import communityRoutes from "./communityRoutes";
import bankRoutes from "./bankRoutes";
import customersRoutes from "./customersRoutes";
import invoiceRoutes from "./invoiceRoutes";
import operationsRoutes from "./operationsRoutes";
import analyticsRoutes from "./analyticsRoutes";

const indexRoutes = express.Router();
indexRoutes.get("/", index);
indexRoutes.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
indexRoutes.use("/users", userRoutes);
indexRoutes.use("/blogs", blogRoutes);
indexRoutes.use("/contact", contactRoutes);
indexRoutes.use("/products", productsRoutes);
indexRoutes.use("/communities", communityRoutes);
indexRoutes.use("/banks", bankRoutes);
indexRoutes.use("/customers", customersRoutes);
indexRoutes.use("/invoices", invoiceRoutes);
indexRoutes.use("/operations", operationsRoutes);
indexRoutes.use("/analytics", analyticsRoutes);
export default indexRoutes;
